### ISSUE TITLE
An example to inference on an image

### ISSUE THREAD

**Issue by fmxiao** [mks0601/TF-SimpleHumanPose#15]
Hi, 

Thank you very much for the work. Can you give an example of how to inference on an image with your pretrained weights? Thanks a lot.

**Comment by jackytu256** [comment]
Hi fmxia,
I am able to provide you some tips so that you can achieve your goal easily.
Firstly, you should grab an object detection pretrain model to predict bbox results as we as resize these bboxes to the image size you utilize to train the simpleHumanPose model, for instance, (192,256), after that, the simpleHumanPose model can be loaded by using like 

```
from config import cfg
import tensorflow as tf
from tfflat.base import Tester
from model import Model

model_path = 140
cfg.set_args("0")
tester = Tester(Model(), cfg)
tester.load_weights(model_path)
```
and then use tester to do the prediction(utilize resize bbox as inputs)
```
heatmap = tester.predict_one([here is the resize bbox])[0]
```
Finally, you just follow the step in the main/test.py file to get the reverse points as "tmpkps".  you can get x,y,score and then you can plot these points(x,y) in the img. Hope this may help.

**Comment by mks0601** [comment]
Thank you @jackytu256. You can also make your own `.json` file if you want to run your own dataset. The `.json` is very easy to make and should follow the format of COCO dataset.

**Comment by wingedrasengan927** [comment]
Hello,
I have used an object detection model to get the bounding box coordinates and the scores.
Now should I used the predict_one method. What arguments does it take?
Thank you.

**Comment by thiranjayamunasinghe** [comment]
@jackytu256 Thank you.
