### ISSUE TITLE
Annotation Set Up 

### ISSUE THREAD

**Issue by xitsleena** [mks0601/TF-SimpleHumanPose#62]
I'm trying to train on PoseTrack but I haven't been able to set up the data directory properly. 

I can't seem to find the json files for the annotations folder. Do you know where to find them? And from the 2018 PoseTrack annotation data (https://posetrack.net/users/download.php), should their given annotations folder be renamed to original_annotations since it has the train, val, test folders?

The posetrack2coco.py also looks in a combined_annotations folder with json files similar to the annotations listed in your directory structure. Are these separate jsons or the same?

**Comment by mks0601** [comment]
Q. Should their given annotations folder be renamed to original_annotations since it has the train, val, test folders?
A. Yes

Q. The posetrack2coco.py also looks in a combined_annotations folder with json files similar to the annotations listed in your directory structure. Are these separate jsons or the same?
A. combined_annotations is what you want. posetrack2coco.py dump json file in combined_annotation.
